version: "3.4"
services:
  minter:
    build:
      context: https://github.com/tokvv/minter-node.git
      args:
        VERSION: 1.0.4
    volumes:
      - /opt/projects/minter-node/data:/minter
    ports:
      - "8841:8841"
      - "3000:3000"
    command: node
